import '../styles/globals.css'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import {Normalize} from 'styled-normalize'
import Navbar from '../components/Navbar'
import React from 'react'
import CartProvider from '../context/Cart'
import Cart from '../components/Cart'
import {useState} from 'react'


function MyApp({ Component, pageProps }) {
  const [isOpen,setIsOpen] = useState(false);
  const openCart = () => {
    setIsOpen(true);
}
const closeCart = () => {
    setIsOpen(false);
}

  return (
   <CartProvider>
    <div className="container">
    <Normalize/>
    <Head>
      <title>E-Commerce</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <div className="page">
      <Navbar cart={isOpen} openCart={openCart}/>
      <Component {...pageProps} />
      <Cart isOpen={isOpen} closeCart={closeCart}/>
    </div>


    <footer>
        <a>
          Sumi J{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>

  </div>
  </CartProvider>
    
  
  
  )
}

export default MyApp
