import '../styles/globals.css'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import {Normalize} from 'styled-normalize'
import Navbar from '../components/Navbar'
import React from 'react'


function MyApp({ Component, pageProps }) {
  return (
   
        <div className="container">
    <Normalize/>
    <Head>
      <title>E-Commerce</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <div className="page">
      <Navbar/>
      <Component {...pageProps} />
    </div>


    <footer>
        <a>
          Sumi J{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>

  </div>

  
  
  )
}

export default MyApp
