import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Message from '../src/components/Message'
import Button from '../src/components/Button'
import { useState, useEffect } from 'react'

export default function Home() {
  const [totalNumberOfClicks, setTotalNumOfClicks] = useState(0);

  useEffect(()=>{
    //the things we want to run when sth changes
 
  },[totalNumberOfClicks])

  const incrementNumberOfClicks = () => {
    setTotalNumOfClicks(totalNumberOfClicks+1);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Button 
          title="You have clicked"
          incrementNumberOfClicks={incrementNumberOfClicks} 
        />
        <Button 
          title="Have you tried clicking?"
          incrementNumberOfClicks={incrementNumberOfClicks} 
        />
        <p>Total: {totalNumberOfClicks}</p>

      </main>

      <footer className={styles.footer}>
        <a>
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
